"""add document acls and access logs

Revision ID: 1a9bf9142a88
Revises: 4991c0effb97
Create Date: 2026-08-15 19:08:55.074876

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a9bf9142a88"
down_revision: str | Sequence[str] | None = "4991c0effb97"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject", sa.String(length=128), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("allowed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_logs")),
    )
    op.create_index(
        op.f("ix_access_logs_created_at"), "access_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_access_logs_document_id"), "access_logs", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_access_logs_subject"), "access_logs", ["subject"], unique=False
    )
    op.create_table(
        "document_acls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("group_name", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_acls_document_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_acls")),
        sa.UniqueConstraint(
            "document_id", "group_name", name=op.f("uq_document_acls_document_id")
        ),
    )
    op.create_index(
        op.f("ix_document_acls_document_id"),
        "document_acls",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_acls_group_name"),
        "document_acls",
        ["group_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_acls_group_name"), table_name="document_acls")
    op.drop_index(op.f("ix_document_acls_document_id"), table_name="document_acls")
    op.drop_table("document_acls")
    op.drop_index(op.f("ix_access_logs_subject"), table_name="access_logs")
    op.drop_index(op.f("ix_access_logs_document_id"), table_name="access_logs")
    op.drop_index(op.f("ix_access_logs_created_at"), table_name="access_logs")
    op.drop_table("access_logs")
    # ### end Alembic commands ###
