"""unique source and external_id

Revision ID: 4991c0effb97
Revises: 0c22dae3d149
Create Date: 2026-08-15 14:11:46.446208

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4991c0effb97"
down_revision: str | Sequence[str] | None = "0c22dae3d149"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_documents_source"), "documents", ["source", "external_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_documents_source"), "documents", type_="unique")
    # ### end Alembic commands ###
